### ISSUE TITLE
Undetermined Bigint conversion when debug enabled

### ISSUE THREAD

**Issue by boin** [queckezz/koa-views#138]
When ctx.state object contains an unserialize type like Bigint, we got an error here.

[ERROR] error - TypeError Do not know how to serialize a BigInt TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at tryStringify (internal/util/inspect.js:1551:17)
    at formatWithOptions (internal/util/inspect.js:1618:25)
    at Object.format (internal/util/inspect.js:1543:10)
    at Function.log (/Documents/projects/pay/node_modules/koa-views/node_modules/debug/src/node.js:190:35)
    at debug (/Documents/projects/pay/node_modules/koa-views/node_modules/debug/src/common.js:114:10)
    at /Documents/projects/pay/node_modules/koa-views/src/index.js:25:9

https://github.com/queckezz/koa-views/blob/a0d1e190a13e4fe055b8851432f7b9e9f213490b/src/index.js#L25

**Comment by int64ago** [comment]
fixed via [v6.2.2](https://github.com/queckezz/koa-views/commit/000168506827dfc5cebbc0a6d8638dd110224d9e)
