### ISSUE TITLE
internal ERROR

### ISSUE THREAD

**Issue by gentlecolder** [queckezz/koa-views#66]
TypeError: undefined is not a function
     at Object.views (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa-views\index.js:105:12)
     at GeneratorFunctionPrototype.next (native)
     at Object.<anonymous> (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\node_modules\koa-compose\index
:19)
     at GeneratorFunctionPrototype.next (native)
     at onFulfilled (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\node_modules\co\index.js:65:19)
     at D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\node_modules\co\index.js:54:5
     at Object.co (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\node_modules\co\index.js:50:10)
     at Object.createPromise (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\node_modules\co\index.js:30:
     at Server.<anonymous> (D:\02_yun_io_Remote\Centralc.nfd8.com5\node_modules\koa\lib\application.js:136:8)
     at Server.emit (events.js:110:17)
     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
     at Socket.socketOnData (_http_server.js:343:22)
     at Socket.emit (events.js:107:17)
     at readableAddChunk (_stream_readable.js:163:16)
     at Socket.Readable.push (_stream_readable.js:126:10)
     at TCP.onread (net.js:538:20)

**Comment by queckezz** [comment]
Not really specific. Can you show me your code where you implement `koa-views` and the respective render call?
